install:
  - cd "./Kweeter-Backend"
  - gradle build -x test
  - cd "./../Kweeter-Frontend"
  - npm install
script:
  - cd "./../Kweeter-Backend"
  - gradle test
  - cd "./../Kweeter-Frontend"
  - npm test