# Generated by Django 2.0.5 on 2018-05-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kweet',
            name='likedBy',
        ),
        migrations.AlterField(
            model_name='kweet',
            name='author',
            field=models.IntegerField(),
        ),
    ]
