# Generated by Django 2.0.5 on 2018-05-31 18:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20180531_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kweet',
            name='publicId',
            field=models.UUIDField(default=uuid.UUID('123ffe1b-b8d0-4001-9636-eaf1de7b220a')),
        ),
    ]
